package torch
package jit

enum TokenKind(val value: Int):
  case TK_DUMMY_START extends TokenKind(256)
  case TK_EOF extends TokenKind(257)
  case TK_WHITESPACE extends TokenKind(258)
  case TK_WHITESPACE_EOF extends TokenKind(259)
  case TK_NUMBER extends TokenKind(260)
  case TK_NEWLINE extends TokenKind(261)
  case TK_INDENT extends TokenKind(262)
  case TK_DEDENT extends TokenKind(263)
  case TK_DEF extends TokenKind(264)
  case TK_EQUIVALENT extends TokenKind(265)
  case TK_IDENT extends TokenKind(266)
  case TK_STRING extends TokenKind(267)
  case TK_STRINGLITERAL extends TokenKind(268)
  case TK_CONST extends TokenKind(269)
  case TK_LIST extends TokenKind(270)
  case TK_DICT extends TokenKind(271)
  case TK_OPTION extends TokenKind(272)
  case TK_APPLY extends TokenKind(273)
  case TK_COMPREHENSION extends TokenKind(274)
  case TK_RANGE_CONSTRAINT extends TokenKind(275)
  case TK_PARAM extends TokenKind(276)
  case TK_INFERRED extends TokenKind(277)
  case TK_ACCESS extends TokenKind(278)
  case TK_ASSIGN extends TokenKind(279)
  case TK_AUG_ASSIGN extends TokenKind(280)
  case TK_ATTRIBUTE extends TokenKind(281)
  case TK_IF extends TokenKind(282)
  case TK_ELSE extends TokenKind(283)
  case TK_ELIF extends TokenKind(284)
  case TK_WHILE extends TokenKind(285)
  case TK_EXPR_STMT extends TokenKind(286)
  case TK_RETURN extends TokenKind(287)
  case TK_IS extends TokenKind(288)
  case TK_ISNOT extends TokenKind(289)
  case TK_NE extends TokenKind(290)
  case TK_EQ extends TokenKind(291)
  case TK_LE extends TokenKind(292)
  case TK_GE extends TokenKind(293)
  case TK_FLOOR_DIV extends TokenKind(294)
  case TK_IF_EXPR extends TokenKind(295)
  case TK_TRUE extends TokenKind(296)
  case TK_FALSE extends TokenKind(297)
  case TK_NONE extends TokenKind(298)
  case TK_AND extends TokenKind(299)
  case TK_OR extends TokenKind(300)
  case TK_NOT extends TokenKind(301)
  case TK_LSHIFT extends TokenKind(302)
  case TK_RSHIFT extends TokenKind(303)
  case TK_CAST extends TokenKind(304)
  case TK_PLUS_EQ extends TokenKind(305)
  case TK_MINUS_EQ extends TokenKind(306)
  case TK_TIMES_EQ extends TokenKind(307)
  case TK_DIV_EQ extends TokenKind(308)
  case TK_MOD_EQ extends TokenKind(309)
  case TK_BIT_OR_EQ extends TokenKind(310)
  case TK_BIT_AND_EQ extends TokenKind(311)
  case TK_BIT_XOR_EQ extends TokenKind(312)
  case TK_LSHIFT_EQ extends TokenKind(313)
  case TK_RSHIFT_EQ extends TokenKind(314)
  case TK_POW_EQ extends TokenKind(315)
  case TK_GLOBAL extends TokenKind(316)
  case TK_BUILT_IN extends TokenKind(317)
  case TK_SUBSCRIPT extends TokenKind(318)
  case TK_VAR extends TokenKind(319)
  case TK_NOTHING extends TokenKind(320)
  case TK_DICT_LITERAL extends TokenKind(321)
  case TK_LIST_LITERAL extends TokenKind(322)
  case TK_TUPLE_LITERAL extends TokenKind(323)
  case TK_FOR extends TokenKind(324)
  case TK_IN extends TokenKind(325)
  case TK_NOTIN extends TokenKind(326)
  case TK_STARRED extends TokenKind(327)
  case TK_UNARY_MINUS extends TokenKind(328)
  case TK_POW extends TokenKind(329)
  case TK_ARROW extends TokenKind(330)
  case TK_DECL extends TokenKind(331)
  case TK_SLICE_EXPR extends TokenKind(332)
  case TK_TYPE_COMMENT extends TokenKind(333)
  case TK_RAISE extends TokenKind(334)
  case TK_ASSERT extends TokenKind(335)
  case TK_DOTS extends TokenKind(336)
  case TK_LIST_COMP extends TokenKind(337)
  case TK_DICT_COMP extends TokenKind(338)
  case TK_BREAK extends TokenKind(339)
  case TK_CONTINUE extends TokenKind(340)
  case TK_DELETE extends TokenKind(341)
  case TK_PASS extends TokenKind(342)
  case TK_CLASS_DEF extends TokenKind(343)
  case TK_IMPORT extends TokenKind(344)
  case TK_WITH extends TokenKind(345)
  case TK_WITH_ITEM extends TokenKind(346)
  case TK_AS extends TokenKind(347)
  case TK_PROP extends TokenKind(348)
  case TK_ELLIPSIS extends TokenKind(349)
  case TK_NONE_TYPE extends TokenKind(350)

  /** 查找并返回与当前value匹配的枚举单例实例，逻辑与Java版`intern()`完全一致
    */
  def intern(): TokenKind =
    TokenKind.values.find(_.value == this.value).getOrElse(this)

  /** 重写toString，返回interned实例的名称（保持与Java行为一致）
    */
//  override def toString(): String = intern().name
